export const FETCH_JS_START = "FETCH_JS_START";
export const FETCH_JS_SUCCESS = "FETCH_JS_SUCCESS";
export const FETCH_JS_FAIL = "FETCH_JS_FAIL";

export const FETCH_JAVA_START = "FETCH_JAVA_START";
export const FETCH_JAVA_SUCCESS = "FETCH_JAVA_SUCCESS";
export const FETCH_JAVA_FAIL = "FETCH_JAVA_FAIL";

export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const RESET_FILTERS = "RESET_FILTERS";

export const SAVE_COMMENT = "SAVE_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
